# Generated by Django 3.2.3 on 2021-06-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210621_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.TextField(default='', max_length=300, null=True),
        ),
    ]
