# Generated by Django 3.1.7 on 2021-07-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210712_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='search.website')),
            ],
            options={
                'ordering': ['?'],
                'unique_together': {('website', 'title')},
            },
        ),
    ]
