# Generated by Django 3.1.7 on 2021-07-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_websitefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDescriptionCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_cards', to='search.website')),
            ],
            options={
                'ordering': ['?'],
                'unique_together': {('website', 'title')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteDescriptionCardFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('description_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='search.websitedescriptioncard')),
            ],
            options={
                'ordering': ['?'],
                'unique_together': {('description_card', 'title')},
            },
        ),
        migrations.DeleteModel(
            name='WebsiteFeature',
        ),
    ]
