# Generated by Django 3.1.7 on 2021-07-19 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20210719_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitydescriptioncardfeature',
            name='icon',
            field=models.FileField(upload_to='media/icons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
