# Generated by Django 3.2.3 on 2021-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210721_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitydescriptioncardfeature',
            name='icon',
        ),
    ]
